"""Agent 4 - the email writer, with RAG.

Input : leads scored "contact" in step 3, the ICP (step 2), the company profile
        (step 1) and the knowledge base built from the company's own website
Output: one checked email draft per lead in data/output/outbox/ (NEVER sent)

For each lead:
  1. Retrieve  : search the knowledge base for the 3 passages closest to the
                 lead's industry and segment (core/kb.py)
  2. Augment   : give the model those passages as numbered SOURCES
  3. Generate  : the model writes an EmailDraft; every claim must cite a
                 source id and copy a quote from it
  4. Check     : code verifies each quote is in its source, numbers come from
                 sources, length is sane, and moderation passes (lesson 5.2)
  5. Assemble  : code adds the signature and the opt-out line

Course lessons used here:
  2.4 Prompt caching    - rules + company profile first (same for every lead)
  2.5 Structured Outputs- EmailDraft with claims tied to sources
  5.2 Moderation        - core/moderation.py before the outbox
"""
from __future__ import annotations

import csv
import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from core.client import ask
from core.grounding import normalize, word_match_share
from core.kb import Chunk, KnowledgeBase
from core.moderation import ModerationResult, moderate
from core.schemas import CompanyProfile, EmailDraft, ICPReport, ICPSegment

_temp = os.getenv("WRITING_TEMPERATURE", "0.5").strip()
WRITING_TEMPERATURE = float(_temp) if _temp else None  # some variety reads more natural
TOP_K = 3
MIN_WORDS, MAX_WORDS = 50, 160

OPT_OUT = "If this isn't relevant for you, just reply \"no thanks\" and we won't write again."
SIMULATION_NOTE = "[SIMULATION - generated by mini-explee for learning. Not sent to anyone.]"

RULES = """You write short, honest B2B cold emails in English for the SENDER company below.

Rules:
- Write to the lead company as a whole ("Hello <company> team"); there is no contact person.
- Tailor the email to the lead's industry, country and signals.
- Every statement about the SENDER (what it does, its customers, any number)
  must come from the numbered SOURCES in the request. List each one in
  "claims" with its source id and an exact quote from that source.
- Use at most 2 claims. If the sources say nothing useful, make no claims.
- Mention a customer name only if it appears in the SOURCES or in
  the sender's named_customers below.
- Never invent numbers, results, awards or customers.
- Never promise results. No pressure, no fake urgency, no ALL CAPS.
- End the body with ONE simple question, e.g. about a short call.
- Do not add a signature or an opt-out line; they are added automatically.

SENDER COMPANY PROFILE:
"""


@dataclass
class WrittenEmail:
    lead_id: str
    company: str
    status: str                      # "ready" | "needs_review"
    subject: str
    text: str                        # the full email, signature included
    draft: EmailDraft
    sources: list[tuple[Chunk, float]]
    issues: list[str] = field(default_factory=list)
    moderation: ModerationResult | None = None


# --- inputs ---------------------------------------------------------------------

def load_contacts(scores_csv: str | Path, leads: list[dict], limit: int | None = None) -> list[tuple[dict, dict]]:
    """(lead, score row) for every lead scored 'contact', best first."""
    by_id = {lead["lead_id"]: lead for lead in leads}
    with Path(scores_csv).open(encoding="utf-8-sig") as f:
        rows = [r for r in csv.DictReader(f) if r["recommendation"] == "contact" and r["lead_id"] in by_id]
    rows.sort(key=lambda r: int(r["fit_score"]), reverse=True)
    pairs = [(by_id[r["lead_id"]], r) for r in rows]
    return pairs[:limit] if limit else pairs


def segment_for(icp: ICPReport, name: str) -> ICPSegment | None:
    return next((s for s in icp.segments if s.name.strip().lower() == name.strip().lower()), None)


def retrieval_query(lead: dict, segment: ICPSegment | None) -> str:
    """What we search the knowledge base for: the lead's world, in plain words."""
    parts = [lead.get("industry", ""), "customer experience"]
    if segment:
        parts += [segment.name, *segment.pain_points[:2]]
    return " ".join(p for p in parts if p)


# --- the request ------------------------------------------------------------------

def instructions_for(profile: CompanyProfile) -> str:
    """Rules + sender profile: identical for every lead -> cacheable prefix."""
    sender = {
        "name": profile.name,
        "one_liner": profile.one_liner,
        "offering": profile.offering,
        "value_props": profile.value_props,
        "named_customers": profile.named_customers,
    }
    return RULES + json.dumps(sender, ensure_ascii=False, indent=1)


def request_input(lead: dict, segment: ICPSegment | None, sources: list[tuple[Chunk, float]]) -> str:
    """The part that changes per lead: who they are, why they fit, the SOURCES."""
    lead_lines = "\n".join(f"{k}: {lead.get(k, '')}" for k in
                           ["company", "industry", "country", "city", "employees", "signals"])
    seg = segment.model_dump_json(include={"name", "pain_points", "buyer_roles"}) if segment else "unknown"
    src = "\n\n".join(f"[{c.id}] (from {c.url})\n{c.text}" for c, _ in sources)
    return f"LEAD:\n{lead_lines}\n\nWHY THEY FIT (segment):\n{seg}\n\nSOURCES:\n{src}"


# --- checks (code, no model) ------------------------------------------------------

NUMBER = re.compile(r"\d+(?:[.,]\d+)?%?")


def check_draft(draft: EmailDraft, sources: list[tuple[Chunk, float]], lead: dict) -> list[str]:
    """Problems a human should look at. Empty list = passes every check."""
    issues = []
    by_id = {c.id: c for c, _ in sources}

    for claim in draft.claims:
        chunk = by_id.get(claim.source_id)
        if chunk is None:
            issues.append(f"claim cites unknown source {claim.source_id!r}: {claim.text}")
            continue
        quote, text = normalize(claim.quote), normalize(chunk.text)
        if quote and quote not in text:
            share, longest = word_match_share(quote, text)
            if share < 0.8 or longest < 0.5:
                issues.append(f"quote not found in {claim.source_id}: {claim.quote}")

    # Any number in the email must come from a source quote or the lead's own data.
    allowed = " ".join([*(c.quote for c in draft.claims), *(c.text for c, _ in sources),
                        str(lead.get("employees", ""))])
    for number in set(NUMBER.findall(draft.body)):
        if number in allowed:
            continue
        if re.search(rf"\b{re.escape(number)}\s*-?\s*min", draft.body):  # "a 15-minute call" is fine
            continue
        issues.append(f"number not found in sources: {number}")

    words = len(draft.body.split())
    if not MIN_WORDS <= words <= MAX_WORDS:
        issues.append(f"body has {words} words (expected {MIN_WORDS}-{MAX_WORDS})")
    if len(draft.subject.split()) > 10:
        issues.append("subject longer than 10 words")
    if draft.subject.isupper():
        issues.append("subject in ALL CAPS")
    return issues


def assemble(draft: EmailDraft, profile: CompanyProfile) -> str:
    """Code, not the model, adds the parts that must always be there and be right."""
    sender = os.getenv("SENDER_NAME", f"The {profile.name} team")
    return (f"Subject: {draft.subject}\n\n{draft.body.strip()}\n\n"
            f"Best regards,\n{sender}\n{profile.name}\n\n{OPT_OUT}")


# --- one email --------------------------------------------------------------------

def write_email(lead: dict, score_row: dict, profile: CompanyProfile, icp: ICPReport, kb: KnowledgeBase,
                *, client=None, moderate_fn=moderate) -> tuple[WrittenEmail, object]:
    segment = segment_for(icp, score_row.get("segment", ""))
    sources = kb.search(retrieval_query(lead, segment), k=TOP_K, client=client)

    extra = {} if WRITING_TEMPERATURE is None else {"temperature": WRITING_TEMPERATURE}
    response = ask(
        request_input(lead, segment, sources),
        task="smart",
        instructions=instructions_for(profile),
        text_format=EmailDraft,
        client=client,
        **extra,
    )
    draft = response.output_parsed
    if draft is None:
        raise RuntimeError(f"No structured output for {lead['lead_id']}. Status: {getattr(response, 'status', '?')}")

    issues = check_draft(draft, sources, lead)
    text = assemble(draft, profile)
    mod = moderate_fn(text)
    if mod.flagged:
        issues.append(f"moderation flagged ({mod.provider}): {', '.join(mod.categories)}")

    email = WrittenEmail(
        lead_id=lead["lead_id"], company=lead.get("company", ""),
        status="ready" if not issues else "needs_review",
        subject=draft.subject, text=text, draft=draft, sources=sources,
        issues=issues, moderation=mod,
    )
    return email, response


# --- outbox -------------------------------------------------------------------------

def save_outbox(emails: list[WrittenEmail], folder: str | Path) -> Path:
    """One .txt per email (what a human reviews) + index.csv (the overview)."""
    folder = Path(folder)
    folder.mkdir(parents=True, exist_ok=True)
    for e in emails:
        lines = [SIMULATION_NOTE, f"To: {e.company} (fictional company, lead {e.lead_id})",
                 f"Status: {e.status}", "", e.text, "", "-" * 60, "Checks:"]
        lines += [f"  ! {issue}" for issue in e.issues] or ["  all passed"]
        lines += ["", "Claims and their sources:"]
        lines += [f"  - {c.text}\n    [{c.source_id}] \"{c.quote}\"" for c in e.draft.claims] or ["  (no claims)"]
        lines += ["", "Retrieved passages (RAG):"]
        lines += [f"  [{c.id}] similarity {s:.2f}  {c.url}" for c, s in e.sources]
        (folder / f"{e.lead_id}.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    with (folder / "index.csv").open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["lead_id", "company", "status", "subject", "claims", "issues", "file"])
        for e in emails:
            writer.writerow([e.lead_id, e.company, e.status, e.subject, len(e.draft.claims),
                             " | ".join(e.issues), f"{e.lead_id}.txt"])
    return folder
